---

name: Flatpak Portal Test App

on:
  push:
    paths-ignore: ['**.md']
    branches: [main]
  pull_request:
    paths-ignore: ['**.md']
    branches: [main]

jobs:
  build-flatpak-gtk3:
    name: GTK3
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build GTK3 portal test
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: portal-test-gtk3.flatpak
          manifest-path: build-aux/org.gnome.PortalTest.Gtk3.json
          cache-key: gtk3-${{ github.sha }}

  build-flatpak-gtk4:
    name: GTK4
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build GTK4 portal test
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: portal-test-gtk4.flatpak
          manifest-path: build-aux/org.gnome.PortalTest.Gtk4.json
          cache-key: gtk4-${{ github.sha }}

  build-flatpak-qt5:
    name: Qt5
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Qt5 portal test
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: portal-test-qt5.flatpak
          manifest-path: build-aux/org.gnome.PortalTest.Qt5.json
          cache-key: qt5-${{ github.sha }}

  build-flatpak-qt6:
    name: Qt6
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Qt6 portal test
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: portal-test-qt6.flatpak
          manifest-path: build-aux/org.gnome.PortalTest.Qt6.json
          cache-key: qt6-${{ github.sha }}
